name: sdist_shiny
channels:
  - conda-forge
  - bioconda
dependencies:
   - pip
   - shiny
   - pandas
   - seaborn
   - setuptools
   - pip:
     - git+https://github.com/simonharnqvist/DISMaL.git#egg=dismal